<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FOS\UserBundle\Model\User;

/**
 * BookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmarkRepository extends EntityRepository
{
    public function findAllBookmarkForUser(User $user)
    {
        return $this->createQueryBuilder('b')
            ->select('b')
            ->where('b.User = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }
}
